version: '3.9'
services:
  database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  web1:
    build:
      context: ./web1
    container_name: web1
    environment:
      DB_HOST: database
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: userdb
    ports:
      - "8081:8080"
    depends_on:
      - database

  web2:
    build:
      context: ./web2
    container_name: web2
    environment:
      DB_HOST: database
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: userdb
    ports:
      - "8082:8080"                                                                                                                                                                                                                                                                                                                                                             
    depends_on:
      - database

  web3:
    build:
      context: ./web3
    container_name: web3
    environment:
      DB_HOST: database
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: userdb
    ports:
      - "8083:8080"
    depends_on:
      - database
